apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: sock-shop-ingress
  namespace: sock-shop
spec:
  rules:
  - host: af66f6a9e408046ea8e4ab8c4d5062da-ca125f39c474b21b.elb.us-west-2.amazonaws.com
    http:
      paths:
      - path: /
        backend:
          serviceName: front-end
          servicePort: 80
