apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: sock-shop-ingress
  namespace: sock-shop
spec:
  rules:
  - host: client1.kube.pro
    http:
      paths:
      - path: /
        backend:
          serviceName: front-end
          servicePort: 80
