apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: carts-ms-cm
  namespace: client2
data:
  JAVA_OPTS: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
  ZIPKIN: zipkin.jaeger.svc.cluster.local
